---
# tasks file for pve-licence

- name: disable warning message (marche pas)
  lineinfile:
    state: present
    dest: /usr/share/pve-manager/js/pvemanagerlib.js
    regexp: ^(\s*)if \((data\.status === 'Active')|(false)\) \{$
    line: "\t\t    if (false) {"

- name: ensure pve-enterprise repo is disable (need a valid subscription)
  file:
    state: absent
    path: "/etc/apt/sources.list.d/pve-enterprise.list"
